CREATE OR REPLACE TABLE DEV_DB.CLEANSED_DNA.CLEANSED_INVENTORY_TRANSACTION AS
SELECT SHA2(
        CONCAT_WS(
            '_',
            COALESCE(INVOICE_NUMBER, 'NA'),
            COALESCE("JC #", 'NA'),
            COALESCE(PART_NO, 'NA')
        )
    ) AS HASH_KEY,
    SHA2(
        CONCAT_WS(
            '_',
            COALESCE(TM_FISCAL_YEAR, 'NA'),
            COALESCE(MONTH_NAME, 'NA'),
            COALESCE(MONTH, 'NA'),
            COALESCE(PARTNER_TYPE, 'NA'),
            COALESCE(DEALER, 'NA'),
            COALESCE(DEALER_CODE, 'NA'),
            COALESCE(DIVISION, 'NA'),
            COALESCE(REGION, 'NA'),
            COALESCE("JC #", 'NA'),
            COALESCE(TO_TIMESTAMP_NTZ(JOB_CARD_CREATED_DATE,'DD-MM-YYYY HH24:MI'),'1900-01-01 00:00'),
            COALESCE(TRY_CAST(JC_OPEN_DAYS AS NUMBER(38, 0)), 0),
            COALESCE(TO_TIMESTAMP_NTZ(JOB_CARD_CLOSED_DATE,'DD-MM-YYYY HH24:MI'),'1900-01-01 00:00'),
            COALESCE(SERVICE_TYPE, 'NA'),
            COALESCE(TRY_CAST(KMS_RUN AS NUMBER(38, 0)), 0),
            COALESCE(PART_NO, 'NA'),
            COALESCE(PART_DESC, 'NA'),
            COALESCE(CATEGORY, 'NA'),
            COALESCE(TM_PART_INDICATOR, 'NA'),
            COALESCE(TRY_CAST(SOLD_QTY AS NUMBER(38, 0)), 0),
            COALESCE(TRY_CAST(TM_SPARES_AMOUNT AS NUMBER(18, 2)),0.00),
            COALESCE(TRY_CAST(SPARES_AMOUNT AS NUMBER(18, 2)), 0.00),
            COALESCE(PPL, 'NA'),
            COALESCE(PL, 'NA'),
            COALESCE(LOB, 'NA'),
            COALESCE(INVOICE_STATUS, 'NA'),
            COALESCE(INVOICE_NUMBER, 'NA'),
            COALESCE(TRY_TO_DATE(INVOICE_DATE, 'DD-MM-YYYY'),'1900-01-01'),
            CASE 
        WHEN UPPER(PART_DESC) ILIKE '%LX%'
        OR PART_DESC ILIKE '%L)%'
        OR PART_DESC ILIKE '%L_)%'
        OR PART_DESC ILIKE '%(L%'
        OR PART_DESC ILIKE '%GMSX%'
        THEN 1
        ELSE 0
       END
        )
    ) AS HASH_ADDRESS,
    COALESCE(TM_FISCAL_YEAR, 'NA') AS TM_FISCAL_YEAR,
    COALESCE(MONTH_NAME, 'NA') AS MONTH_NAME,
    COALESCE(MONTH, 'NA') AS MONTH,
    COALESCE(PARTNER_TYPE, 'NA') AS PARTNER_TYPE,
    COALESCE(DEALER, 'NA') AS DEALER,
    COALESCE(DEALER_CODE, 'NA') AS DEALER_CODE,
    COALESCE(DIVISION, 'NA') AS DIVISION,
    COALESCE(REGION, 'NA') AS REGION,
    COALESCE("JC #", 'NA') AS JOB_CARD_NUMBER,
    -- Convert VARCHAR to TIMESTAMP_NTZ, handling invalid dates
    COALESCE(TRY_TO_TIMESTAMP_NTZ(JOB_CARD_CREATED_DATE,'DD-MM-YYYY HH24:MI'),'1900-01-01 00:00') AS JOB_CARD_CREATED_DATE,
    -- Convert VARCHAR to NUMBER, replacing NULLs with 0
    COALESCE(TRY_CAST(JC_OPEN_DAYS AS NUMBER(38, 0)), 0) AS JC_OPEN_DAYS,
    -- Convert VARCHAR to TIMESTAMP_NTZ, handling invalid dates
    COALESCE(TRY_TO_TIMESTAMP_NTZ(JOB_CARD_CLOSED_DATE,'DD-MM-YYYY HH24:MI'),'1900-01-01 00:00') AS JOB_CARD_CLOSED_DATE,
    COALESCE(SERVICE_TYPE, 'NA') AS SERVICE_TYPE,
    -- Convert VARCHAR to NUMBER, replacing NULLs with 0
    COALESCE(TRY_CAST(KMS_RUN AS NUMBER(38, 0)), 0) AS KMS_RUN,
    COALESCE(PART_NO, 'NA') AS PART_NO,
    COALESCE(PART_DESC, 'NA') AS PART_DESC,
    COALESCE(CATEGORY, 'NA') AS CATEGORY,
    COALESCE(TM_PART_INDICATOR, 'NA') AS TM_PART_INDICATOR,
    -- Convert VARCHAR to NUMBER, replacing NULLs with 0
    COALESCE(TRY_CAST(SOLD_QTY AS NUMBER(38, 0)), 0) AS SOLD_QTY,
    -- Convert VARCHAR to DECIMAL (handling NULLs)
    COALESCE(TRY_CAST(TM_SPARES_AMOUNT AS NUMBER(18, 2)),0.00) AS TM_SPARES_AMOUNT,
    COALESCE(TRY_CAST(SPARES_AMOUNT AS NUMBER(18, 2)), 0.00) AS SPARES_AMOUNT,
    COALESCE(PPL, 'NA') AS PPL,
    COALESCE(PL, 'NA') AS PL,
    COALESCE(LOB, 'NA') AS LOB,
    COALESCE(INVOICE_STATUS, 'NA') AS INVOICE_STATUS,
    COALESCE(INVOICE_NUMBER, 'NA') AS INVOICE_NUMBER,
    -- Convert VARCHAR to DATE, handling invalid dates
    COALESCE(TRY_TO_DATE(INVOICE_DATE, 'DD-MM-YYYY'),'1900-01-01') AS INVOICE_DATE,
    CASE 
        WHEN UPPER(PART_DESC) ILIKE '%LX%'
      OR PART_DESC ILIKE '%L)%'
      OR PART_DESC ILIKE '%L_)%'
      OR PART_DESC ILIKE '%(L%'
      OR PART_DESC ILIKE '%GMSX%'
      THEN 1
        ELSE 0
       END AS liquid_flag,
    CONVERT_TIMEZONE('UTC', 'Asia/Kolkata', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS CREATED_DATE,
    CONVERT_TIMEZONE('UTC', 'Asia/Kolkata', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS MODIFIED_DATE
    FROM DEV_DB.SDL_RAW.SDL_INVENTORY_TRANSACTION;